#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/labdesk/labdesk /usr/bin/labdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/labdesk.service ]; then
			rm /etc/systemd/system/labdesk.service /usr/lib/systemd/system/labdesk.service /usr/lib/systemd/user/labdesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/labdesk/files/systemd/labdesk.service /usr/lib/systemd/system/labdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload labdesk.service: Unit labdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/labdesk.service:10: Executable path is not absolute: pkill -f "labdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/labdesk.service
		fi
		systemctl daemon-reload
		systemctl enable labdesk
		systemctl start labdesk
	fi
fi
